apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cinder-ssd
provisioner: cinder.csi.openstack.org
parameters:
  type: SSD  # Ajusta esto según los tipos de volumen disponibles en tu OpenStack
  availability: nova  # Ajusta a tu zona de disponibilidad
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer