apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-token
type: Opaque
data:
  token: eyJhIjoiNWI4ZDNlM2I2ZDE4OThkMmFhYWY3MWRlNmY2ODk2MjEiLCJ0IjoiY2RlNWJlYmItNDA4NS00YzYzLWI4ZjktYmRlODc4NTY1Y2JiIiwicyI6IllUVmhOVGMwTXpndE0ySmlOUzAwWXpJMkxUZ3dNVGt0T1Raa1ptUTFNalk0WkdaaiJ9