apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-chatbot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi-chatbot
  template:
    metadata:
      labels:
        app: fastapi-chatbot
    spec:
      containers:
      - name: fastapi-chatbot
        image: orlandogtp/fastapi-chatbot:v1.0.3
        command: ["uvicorn"]
        args: ["app.main:app", "--host", "0.0.0.0", "--port", "8000"]
        ports:
        - containerPort: 8000
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: chatbot-secrets
              key: OPENAI_API_KEY
        - name: TAVILY_API_KEY
          valueFrom:
            secretKeyRef:
              name: chatbot-secrets
              key: TAVILY_API_KEY
        - name: CONFIG_FILE
          valueFrom:
            secretKeyRef:
              name: chatbot-secrets
              key: CONFIG_FILE
        - name: DOC_PATH
          valueFrom:
            secretKeyRef:
              name: chatbot-secrets
              key: DOC_PATH
        - name: LANGCHAIN_PROJECT
          valueFrom:
            secretKeyRef:
              name: chatbot-secrets
              key: LANGCHAIN_PROJECT
        - name: LANGCHAIN_API_KEY
          valueFrom:
            secretKeyRef:
              name: chatbot-secrets
              key: LANGCHAIN_API_KEY
        - name: LANGCHAIN_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: chatbot-secrets
              key: LANGCHAIN_ENDPOINT
        - name: LANGCHAIN_TRACING_V2
          valueFrom:
            secretKeyRef:
              name: chatbot-secrets
              key: LANGCHAIN_TRACING_V2
        - name: QDRANT_URL
          valueFrom:
            secretKeyRef:
              name: chatbot-secrets
              key: QDRANT_URL
        - name: QDRANT_API_KEY
          valueFrom:
            secretKeyRef:
              name: chatbot-secrets
              key: QDRANT_API_KEY
        - name: COLLECTION_NAME
          valueFrom:
            secretKeyRef:
              name: chatbot-secrets
              key: COLLECTION_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: chatbot-secrets
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: chatbot-secrets
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: chatbot-secrets
              key: DB_NAME
        - name: DB_HOST
          value: "postgresql"  # o el nombre de tu servicio de base de datos
        - name: DB_PORT
          value: "5432"