apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-kubeconfig
  namespace: default
data:
  kubeconfig: |
    apiVersion: v1
    kind: Config
    clusters:
    - cluster:
        server: $KUBERNETES_API_SERVER
        certificate-authority-data: $CA_CERT
      name: kubernetes
    contexts:
    - context:
        cluster: kubernetes
        user: jenkins
      name: jenkins-context
    current-context: jenkins-context
    users:
    - name: jenkins
      user:
        token: $TOKEN
