apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base/redis/deployment.yaml
- ../base/redis/service.yaml
- ../base/celery/deployment.yaml
- ../base/app/deployment.yaml
- ../base/app/service.yaml

namePrefix: local-

images:
- name: orlandogtp/fastapi-chatbot
  newTag: latest

configMapGenerator:
- name: app-config
  literals:
  - ENVIRONMENT=local

secretGenerator:
- name: chatbot-secrets
  env: secrets.env